### ISSUE TITLE
How can I give feedback? 

### ISSUE THREAD

**Issue by sshantt** [sr229/cdr-web-lkgr#1]
I gave this build a try. Where do I leave feedback about what works and what doesn't?

**Comment by sr229** [comment]
Thanks for asking! Head over to cdr/code-server#857 and let the Coder folks know what works and what doesn't.

Happy hacking!

**Comment by sr229** [comment]
We've merged the web branch today so just report normally via Issues in code-server from now on. Thanks for helping us test!
