### ISSUE TITLE
Where are the ARM builds?

### ISSUE THREAD

**Issue by Akarys42** [sr229/cdr-web-lkgr#2]
Hi, 
I probably have missed something, but I can’t find the ARM builds in the release tab. 
Do I have to build them myself, or re-setup the CI or somethings?
Thanks!

**Comment by sr229** [comment]
Still waiting on ARM support upstream so we can't proceed without nbin supporting it first.

**Comment by Akarys42** [comment]
Okay so we need to wait until the nbin PR is merged?

>

**Comment by sr229** [comment]
Yep. We're still waiting on that however.

**Comment by sr229** [comment]
ARM builds are now being built. We ride to dawn my dudes

**Comment by Akarys42** [comment]
Oh yeah that's cool! Are they already released, or they are still building?
